name: trivy-security-scanning
on: push

permissions:
  security-events: write # To upload sarif files

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Get version
        id: vars
        run: pwd; ls -la
      
      - name: Build an image from Dockerfile
        run: |
          docker build -t app .
      - name: Get version
        id: vars1
        run: pwd; ls -la
      
      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: 'app'
          ignore-unfixed: true
          vuln-type: 'os,library'
          severity: 'CRITICAL, HIGH, MEDIUM, LOW'
          format: 'sarif'
          output: 'trivy-results.sarif'
          
      - name: Upload Trivy scan results to GitHub Security tab
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: 'trivy-results.sarif'
          category: 'code'
          
          
          
